// WARNING: DO NOT DELETE THIS FILE
// This file was auto-generated by the Witnet compiler, any manual changes will be overwritten.
const WitnetRequestBoardProxy = artifacts.require("WitnetRequestBoardProxy")
const WitnetRequestBoard = artifacts.require("WitnetRequestBoard")
const CBOR = artifacts.require("CBOR")
const Witnet = artifacts.require("Witnet")

const addresses = {
  "goerli": {
    "CBOR": "0x9905821089928e5A26841225510cea8B2984F6D8",
    "Witnet": "0x5259aCEfF613b37aF35999798A6da60bEF326038",
    "WitnetRequestBoardProxy": "0x9b42b0D80C428B17A5828dF5C2c96454ca54bD04",
  },
  "rinkeby": {
    "CBOR": "0xa3AFD68122a21c7D21Ddd95E5c077f958dA46662",
    "Witnet": "0x14a2C568AF4F3fa834C907cC08E2C6c5019daaC1",
    "WitnetRequestBoardProxy": "0x3F993030e2ba6473B5AaC2DaEA4A64b05500Ac8B",
  },
}

module.exports = function (deployer, network, accounts) {
  network = network.split("-")[0]
  if (network in addresses) {
    Witnet.address = addresses[network]["Witnet"]
    WitnetRequestBoardProxy.address = addresses[network]["WitnetRequestBoardProxy"]
  } else {
    deployer.deploy(CBOR)
    deployer.link(CBOR, Witnet)
    deployer.deploy(Witnet)
    deployer.deploy(WitnetRequestBoard, [accounts[0]]).then(function() {
      return deployer.deploy(WitnetRequestBoardProxy, WitnetRequestBoard.address)
    })

  }
}
